# training
train:
  eval_freq: 1000
  batch_size: 250
  epochs: 1000
  save_locally: False

metrics:
  wasserstein_error: 1
  w_one_ahead: True
  w_cumulative: False

#WandB
wandb:
  save_plots: False
  save_model: False

# models
energy:
  # optimization
  optim:
    weight_decay: 0.0
    optimizer: Adam
    lr: 0.001
    beta1: 0.9
    beta2: 0.999
    eps: 0.00000001
    grad_clip: 10.0

  # model architecture
  model:
    layers: [64, 64]

  # for linear parameterization
  linear:
    reg: 0.01
    features:
      polynomials:
        degree: 4
        sines: False # Mix also with sines
        cosines: False # Mix also with cosines
      rbfs: 
        n_centers_per_dim: 10
        domain: [-4, 4]
        sigma: 0.5
        # types of rbfs to include
        types: [
          # 'linear',
          # 'thin_plate_spline',
          # 'cubic',
          # 'quintic',
          'const',
          # 'multiquadric',
          # 'inverse_multiquadric',
          # 'inverse_quadratic'
        ]
      